project:
  type: website

website:
  title: "Web"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutoWeb.qmd
        text: Tutorial Web
      - href: tutoNet.qmd
        text: Tutorial Netlify

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
